# Railway Project Configuration
# This file helps Railway understand how to deploy your application

[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "python railway_test.py"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
