# Logstash Helm Chart Values
replicas: 2

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-master:9200"]

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      http {
        port => 8080
      }
    }
    
    filter {
      if [kubernetes] {
        mutate {
          add_field => { "kubernetes_namespace" => "%{[kubernetes][namespace]}" }
          add_field => { "kubernetes_pod" => "%{[kubernetes][pod][name]}" }
          add_field => { "kubernetes_container" => "%{[kubernetes][container][name]}" }
        }
      }
      
      # Parse JSON logs
      if [message] =~ /^\{.*\}$/ {
        json {
          source => "message"
        }
      }
      
      # Add timestamp
      date {
        match => [ "timestamp", "ISO8601" ]
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      
      # Debug output
      stdout {
        codec => rubydebug
      }
    }

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

extraEnvs:
  - name: LS_JAVA_OPTS
    value: "-Xmx${logstash_heap_size} -Xms${logstash_heap_size}"

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
    - name: http
      port: 8080
      protocol: TCP
    - name: monitoring
      port: 9600
      protocol: TCP

nodeSelector:
  node-type: monitoring

tolerations:
  - key: "monitoring"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Persistence for Logstash data
persistence:
  enabled: true
  storageClass: gp2
  size: 20Gi

# Security Context
securityContext:
  fsGroup: 1000
  runAsUser: 1000

# Readiness and Liveness probes
livenessProbe:
  httpGet:
    path: /
    port: 9600
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: 9600
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 3
