[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'pwd',
  'ls -la',
  'echo "Installing dependencies..."',
  'npm ci'
]

[phases.build]
cmds = [
  'echo "Building application..."',
  'pwd', 
  'ls -la',
  'npm run build'
]

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'