-- Sample integrations data
INSERT INTO integrations (id, name, displayName, description, category, type, configSchema, iconUrl, documentationUrl, isActive, isPublic, version, createdByUserId, createdAt, updatedAt) VALUES 
('salesforce', 'salesforce', 'Salesforce CRM', 'Connect your Kennex system with Salesforce to sync contacts, leads, and opportunities', 'CRM', 'OAUTH', '{"clientId": {"type": "string", "required": true}, "clientSecret": {"type": "string", "required": true}}', 'https://www.salesforce.com/content/dam/web/en_us/www/images/sfdc-logo.svg', 'https://developer.salesforce.com/', true, true, '1.0.0', 'admin-user', datetime('now'), datetime('now')),
('hubspot', 'hubspot', 'HubSpot CRM', 'Integrate with HubSpot to manage your customer relationships and marketing campaigns', 'CRM', 'OAUTH', '{"clientId": {"type": "string", "required": true}, "clientSecret": {"type": "string", "required": true}}', 'https://www.hubspot.com/hubfs/HubSpot_Logos/HubSpot-Inversed-Favicon.png', 'https://developers.hubspot.com/', true, true, '1.2.0', 'admin-user', datetime('now'), datetime('now')),
('mailchimp', 'mailchimp', 'Mailchimp', 'Sync your contact lists and automate email marketing campaigns with Mailchimp', 'EMAIL', 'OAUTH', '{"clientId": {"type": "string", "required": true}, "clientSecret": {"type": "string", "required": true}}', 'https://mailchimp.com/release/plums/cxp/images/apple-touch-icon-192.png', 'https://mailchimp.com/developer/', true, true, '2.1.0', 'admin-user', datetime('now'), datetime('now')),
('twilio', 'twilio', 'Twilio SMS', 'Send SMS messages and manage phone communications through Twilio', 'SMS', 'API_KEY', '{"accountSid": {"type": "string", "required": true}, "authToken": {"type": "string", "required": true}}', 'https://www.twilio.com/content/dam/twilio-com/global/en/other/twilio-logo-red.svg', 'https://www.twilio.com/docs', true, true, '1.5.0', 'admin-user', datetime('now'), datetime('now')),
('slack', 'slack', 'Slack Webhooks', 'Send notifications and alerts to your Slack channels', 'WEBHOOK', 'WEBHOOK', '{"webhookUrl": {"type": "string", "required": true}}', 'https://a.slack-edge.com/80588/marketing/img/meta/slack_hash_256.png', 'https://api.slack.com/messaging/webhooks', true, true, '1.0.0', 'admin-user', datetime('now'), datetime('now')),
('google-analytics', 'google_analytics', 'Google Analytics', 'Track and analyze user interactions and campaign performance', 'ANALYTICS', 'OAUTH', '{"clientId": {"type": "string", "required": true}, "clientSecret": {"type": "string", "required": true}}', 'https://www.google.com/analytics/images/google-analytics-logo.svg', 'https://developers.google.com/analytics', true, true, '4.0.0', 'admin-user', datetime('now'), datetime('now'));

-- First create the admin user if it doesn't exist
INSERT OR IGNORE INTO users (id, email, username, firstName, lastName, role, isActive, passwordHash, createdAt, updatedAt) VALUES 
('admin-user', 'admin@example.com', 'admin', 'System', 'Administrator', 'ADMIN', true, '$2b$10$dummy.hash.for.sample.data', datetime('now'), datetime('now'));

-- Sample connections
INSERT INTO integration_connections (id, integrationId, userId, name, status, lastSyncAt, syncCount, isActive, configData, createdAt, updatedAt) VALUES 
('conn-1', 'salesforce', 'admin-user', 'Production Salesforce', 'ACTIVE', datetime('now', '-2 hours'), 150, true, '{"instanceUrl": "https://mycompany.salesforce.com", "clientId": "3MVG9..."}', datetime('now'), datetime('now')),
('conn-2', 'hubspot', 'admin-user', 'Marketing HubSpot', 'ACTIVE', datetime('now', '-1 hour'), 75, true, '{"portalId": "12345678", "accessToken": "CL..."}', datetime('now'), datetime('now')),
('conn-3', 'mailchimp', 'admin-user', 'Newsletter List', 'INACTIVE', datetime('now', '-1 day'), 25, false, '{"audienceId": "abc123def", "server": "us19"}', datetime('now'), datetime('now')),
('conn-4', 'twilio', 'admin-user', 'SMS Gateway', 'ERROR', datetime('now', '-3 hours'), 200, true, '{"accountSid": "AC...", "errorMessage": "Invalid credentials"}', datetime('now'), datetime('now'));

-- Sample webhooks
INSERT INTO webhooks (id, connectionId, name, url, method, events, isActive, successCount, failureCount, lastTriggeredAt, lastSuccessAt, lastFailureAt, headers, timeout, createdByUserId, createdAt, updatedAt) VALUES 
('webhook-1', 'conn-1', 'Lead Notifications', 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX', 'POST', '["lead.created", "lead.updated"]', true, 145, 5, datetime('now', '-30 minutes'), datetime('now', '-30 minutes'), datetime('now', '-2 hours'), '{"Content-Type": "application/json"}', 30, 'admin-user', datetime('now'), datetime('now')),
('webhook-2', 'conn-2', 'Contact Updates', 'https://myapp.com/api/webhooks/hubspot', 'POST', '["contact.created", "deal.updated"]', true, 89, 2, datetime('now', '-1 hour'), datetime('now', '-1 hour'), datetime('now', '-1 day'), '{"Authorization": "Bearer token123"}', 30, 'admin-user', datetime('now'), datetime('now')),
('webhook-3', null, 'Campaign Alerts', 'https://discord.com/api/webhooks/123456789/abcdefghijk', 'POST', '["campaign.started", "campaign.completed"]', false, 0, 3, null, null, datetime('now', '-2 days'), '{"Content-Type": "application/json"}', 30, 'admin-user', datetime('now'), datetime('now'));