
# Frontier Module Orchestration Configuration
orchestration:
  router:
    # Router configuration
    max_concurrent_requests: 1000
    request_timeout: 30.0
    enable_request_queuing: true
    queue_size: 10000
    
    # Classification settings
    classification:
      confidence_threshold: 0.8
      use_user_history: true
      history_window: 10
      keyword_weight: 0.4
      context_weight: 0.3
      user_history_weight: 0.2
      metadata_weight: 0.1
    
    # Confidence scoring
    confidence_scoring:
      quality_weights:
        relevance: 0.25
        coherence: 0.20
        accuracy: 0.20
        completeness: 0.15
        safety: 0.10
        performance: 0.10
      
      # Historical performance tracking
      enable_history_tracking: true
      max_history_size: 1000
      
      # Time factor calculation
      optimal_response_time_min: 0.1
      optimal_response_time_max: 2.0
      slow_response_threshold: 10.0

  # Communication protocols
  communication:
    protocols:
      http:
        enabled: true
        base_timeout: 30.0
        max_retries: 3
        retry_delay: 1.0
      
      websocket:
        enabled: true
        connection_timeout: 10.0
        heartbeat_interval: 30.0
      
      message_broker:
        enabled: true
        type: "redis"
        host: "redis.frontier.svc.cluster.local"
        port: 6379
        queue_prefix: "frontier"
    
    # Security settings
    security:
      enable_authentication: true
      enable_encryption: false  # Set to true in production
      rate_limiting:
        enabled: true
        max_requests_per_minute: 1000
        window_minutes: 1
      
      # Module authentication
      module_auth:
        required_fields:
          - module_id
          - api_key
          - signature
        token_expiry_hours: 24

  # Dynamic loading configuration
  dynamic_loading:
    enabled: true
    strategy: "on_demand"  # on_demand, predictive, preemptive, scheduled
    
    # Loading thresholds
    auto_load_threshold: 10  # requests before auto-loading
    max_concurrent_loads: 3
    module_idle_timeout_minutes: 30
    health_check_interval_seconds: 30
    
    # Kubernetes configuration
    kubernetes:
      namespace: "frontier-modules"
      config_type: "in_cluster"  # in_cluster or local
      default_resource_limits:
        cpu: "2000m"
        memory: "4Gi"
        gpu: "1"
      default_resource_requests:
        cpu: "1000m" 
        memory: "2Gi"
    
    # Predictive loading
    predictive:
      enable_usage_prediction: true
      prediction_window_minutes: 15
      confidence_threshold: 0.7
      pattern_analysis_days: 7

  # Fallback and resilience
  fallback:
    enabled: true
    default_confidence_threshold: 0.6
    default_success_rate_threshold: 0.8
    
    # Circuit breaker settings
    circuit_breaker:
      enabled: true
      failure_threshold: 5
      recovery_timeout_seconds: 60
      half_open_max_calls: 3
    
    # Health monitoring
    health_monitoring:
      enabled: true
      monitoring_window_seconds: 300
      min_success_rate: 0.8
      max_response_time_ms: 5000
      min_availability: 0.95
    
    # Adaptive learning
    adaptive_learning:
      enabled: true
      adaptation_window: 100
      learning_rate: 0.1
      performance_history_size: 1000

# Module specifications
modules:
  foundation:
    module_id: "foundation"
    module_type: "foundation"
    image: "frontier/foundation-model"
    version: "1.0.0"
    endpoint_pattern: "http://{service_name}.{namespace}.svc.cluster.local:8080"
    
    resource_requirements:
      requests:
        cpu: "4000m"
        memory: "16Gi"
        nvidia.com/gpu: "2"
      limits:
        cpu: "8000m"
        memory: "32Gi"
        nvidia.com/gpu: "2"
    
    scaling:
      min_replicas: 2
      max_replicas: 10
      target_cpu_utilization: 70
    
    health_check:
      path: "/health"
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3

  business-operations:
    module_id: "business-operations"
    module_type: "business"
    image: "frontier/business-module"
    version: "1.0.0"
    
    resource_requirements:
      requests:
        cpu: "2000m"
        memory: "8Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "4000m"
        memory: "16Gi"
        nvidia.com/gpu: "1"
    
    scaling:
      min_replicas: 1
      max_replicas: 5
      target_cpu_utilization: 70
    
    dependencies:
      - foundation
    
    environment_variables:
      SPECIALIZED_DOMAIN: "business"
      FOUNDATION_MODEL_ENDPOINT: "http://foundation.frontier-modules.svc.cluster.local:8080"

  web-development:
    module_id: "web-development"
    module_type: "development"
    image: "frontier/development-module"
    version: "1.0.0"
    
    resource_requirements:
      requests:
        cpu: "2000m"
        memory: "8Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "6000m"
        memory: "20Gi"
        nvidia.com/gpu: "1"
    
    scaling:
      min_replicas: 1
      max_replicas: 8
      target_cpu_utilization: 70
    
    dependencies:
      - foundation

  marketing-creative:
    module_id: "marketing-creative"
    module_type: "creative"
    image: "frontier/creative-module"
    version: "1.0.0"
    
    resource_requirements:
      requests:
        cpu: "2000m"
        memory: "8Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "4000m"
        memory: "16Gi"
        nvidia.com/gpu: "1"
    
    scaling:
      min_replicas: 1
      max_replicas: 6
      target_cpu_utilization: 70
    
    dependencies:
      - foundation
      - multimodal-processor

  multimodal-processor:
    module_id: "multimodal-processor"
    module_type: "multimodal"
    image: "frontier/multimodal-module"
    version: "1.0.0"
    
    resource_requirements:
      requests:
        cpu: "3000m"
        memory: "12Gi"
        nvidia.com/gpu: "2"
      limits:
        cpu: "6000m"
        memory: "24Gi"
        nvidia.com/gpu: "2"
    
    scaling:
      min_replicas: 1
      max_replicas: 4
      target_cpu_utilization: 75

# Fallback rules configuration
fallback_rules:
  business-operations:
    - trigger_conditions:
        - "timeout"
        - "low_confidence"
        - "service_unavailable"
      fallback_modules:
        - "foundation"
      strategy: "adaptive"
      priority: 1
      quality_threshold: 0.7
      max_retries: 2
      retry_delay: 1.0

  web-development:
    - trigger_conditions:
        - "error_response"
        - "timeout"
        - "quality_threshold_not_met"
      fallback_modules:
        - "foundation"
      strategy: "sequential"
      priority: 1
      quality_threshold: 0.6
      max_retries: 3
      retry_delay: 0.5

  marketing-creative:
    - trigger_conditions:
        - "low_confidence"
        - "service_unavailable"
      fallback_modules:
        - "foundation"
      strategy: "sequential"
      priority: 1
      quality_threshold: 0.5
      max_retries: 2
      retry_delay: 1.0

  multimodal-processor:
    - trigger_conditions:
        - "timeout"
        - "error_response"
        - "resource_exhaustion"
      fallback_modules:
        - "foundation"
      strategy: "adaptive"
      priority: 1
      quality_threshold: 0.6
      max_retries: 2
      retry_delay: 2.0

# Monitoring and observability
monitoring:
  enabled: true
  
  metrics:
    # Module performance metrics
    module_metrics:
      - "request_count"
      - "response_time"
      - "error_rate"
      - "confidence_score"
      - "throughput"
      - "queue_depth"
    
    # System-level metrics
    system_metrics:
      - "total_requests"
      - "active_connections"
      - "memory_usage"
      - "cpu_utilization"
      - "gpu_utilization"
    
    # Fallback metrics
    fallback_metrics:
      - "fallback_rate"
      - "fallback_success_rate"
      - "circuit_breaker_state"
      - "failure_types"
  
  # Export configuration
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
  
  # Alerting rules
  alerts:
    high_error_rate:
      condition: "error_rate > 0.1"
      duration: "5m"
      severity: "warning"
    
    module_unavailable:
      condition: "module_health == 0"
      duration: "1m" 
      severity: "critical"
    
    high_response_time:
      condition: "avg_response_time > 5000"
      duration: "3m"
      severity: "warning"
    
    circuit_breaker_open:
      condition: "circuit_breaker_state == 'OPEN'"
      duration: "0m"
      severity: "warning"

# Deployment configuration
deployment:
  environment: "production"  # development, staging, production
  
  # API Gateway
  gateway:
    enabled: true
    replicas: 3
    image: "frontier/api-gateway"
    version: "1.0.0"
    
    ingress:
      enabled: true
      host: "api.frontier.ai"
      tls_enabled: true
      certificate_issuer: "letsencrypt-prod"
    
    rate_limiting:
      enabled: true
      requests_per_second: 1000
      burst_size: 2000
  
  # Load balancer
  load_balancer:
    type: "nginx"
    algorithm: "round_robin"
    health_check_path: "/health"
    health_check_interval: 10
    
  # Service mesh (optional)
  service_mesh:
    enabled: false
    type: "istio"
    mtls_enabled: true
